# =========================
# SAP HANA Cloud Connection
# =========================

spring.datasource.url=jdbc:sap://8da9a4e0-377e-4b29-a223-fe716e464344.hna1.prod-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true

spring.datasource.username=DBADMIN
spring.datasource.password=AppleBall@1234

spring.datasource.driver-class-name=com.sap.db.jdbc.Driver


# =========================
# JPA / Hibernate
# =========================

spring.jpa.database-platform=org.hibernate.dialect.HANAColumnStoreDialect

# create/update tables automatically
spring.jpa.hibernate.ddl-auto=update

# optional (for logs)
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# optional
server.port=8080

























## =========================
## SAP HANA Cloud Connection
## =========================
#
#spring.datasource.url=jdbc:sap://8da9a4e0-377e-4b29-a223-fe716e464344.hna1.prod-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=6CF2BF3AFC504B79A810609D0DA8027E
#
#spring.datasource.username=6CF2BF3AFC504B79A810609D0DA8027E_1TMH4AX27VASGC7BPLX8LE0ZN_RT
#
#spring.datasource.password=CvD:5bRe,% n{#=6R(Q1iDSdG.S:0@s/x</@P7=5o}u=e?*T! LSF;N:jnNbAaMoICDG<?b&:K0B-6=;KOTgJa=|KJxA3{8ZO0Y;{P]aZ447pK##.TJUvK1q*VJR#Y]c
#
#spring.datasource.driver-class-name=com.sap.db.jdbc.Driver
#
#
## =========================
## JPA / Hibernate
## =========================
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## Optional - comment temporarily if issue comes
## spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HANADialect