# ===== SAP HANA Connection =====
spring.datasource.url=jdbc:sap://6b7e2e31-0937-4af0-8bb1-ed9247f101df.hna1.prod-us10.hanacloud.ondemand.com:443/?encrypt=true&validateCertificate=true&currentschema=AE07243D5F184820887CA86ECEB6A870
spring.datasource.username=AE07243D5F184820887CA86ECEB6A870_10GON2HHL06LSGNBHY4XXLBYK_RT
spring.datasource.password=~w0f_R^P(D,xRZfPBEsTdS=Emh?%qvP~HxA4v%wCSO_FETGip1)0!~p<(G2uxY1?9.Iwn!TWT^0R50e0;Pf:AK4(PZ.DzZCkUF=sN}+s@^#/-=5,]r3IJ8=E=eKsUKaW
spring.datasource.driver-class-name=com.sap.db.jdbc.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HANADialect
spring.jpa.properties.hibernate.format_sql=true

# ===== Server Port =====
server.port=${PORT:8080}